@host = 127.0.0.1:8443

### Suche alle Artikel
https://{{host}}/articles

### Suche mit vorhandener Artikel-ID
https://{{host}}/articles/7637ca05-0cd5-48a4-a03e-3ada51cee420

### Suche mit vorhandenem Hersteller
https://{{host}}/articles?manufacturer=aute

### Suche mit vorhandener EAN
https://{{host}}/articles?ean=781641

### Neuen Artikel anlegen
POST https://{{host}}/articles
Content-Type: application/json

< .\article-new.json

### Neuen fehlerhaften Artikel anlegen
POST https://{{host}}/articles
Content-Type: application/json

< .\article-new-invalid.json

### Loeschen eines vorhandenen Artikels
DELETE https://{{host}}/articles/7637ca05-0cd5-48a4-a03e-3ada51cee420
