@host = 127.0.0.1:8443

### Hello World
http://{{host}}

### Suche alle Artikel
https://{{host}}/articles

### Neuen Artikel anlegen
POST https://{{host}}/articles
Content-Type: application/json

< .\article-new.json

### Neuen fehlerhaften Artikel anlegen
POST https://{{host}}/articles
Content-Type: application/json

< .\article-new-invalid.json